steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nectar-gdg:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nectar-gdg:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - nectar-gdg
      - '--image=gcr.io/$PROJECT_ID/nectar-gdg:$COMMIT_SHA'
      - '--region=us-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-secrets=CANOPY_API_KEY=CANOPY_API_KEY:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest,GOOGLE_PLACES_API_KEY=GOOGLE_PLACES_API_KEY:latest,SCRAPERAPI_KEY=SCRAPERAPI_KEY:latest,NECTAR_API_SECRET=NECTAR_API_SECRET:latest'

options:
  logging: CLOUD_LOGGING_ONLY
